/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: c06f42313ca1d2ab65f61905cdbc0c2e)
interface __BaseEnv_CloudflareBindings {
	GALLERY_BUCKET: R2Bucket;
	IMAGES: ImagesBinding;
	CF_ACCESS_TEAM_DOMAIN: "https://chanyakushima.cloudflareaccess.com";
	CF_ACCESS_AUD: "08f4b21524ee5e79efaaa746e84959d1270a483459856b45c9aeb180e4c0941c";
	GALLERY_ENVIRONMENT: "preview" | "production";
	GALLERY_CANONICAL_HOST: "chanya.jp";
	GALLERY_ADMIN_EMAIL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface PreviewEnv {
		GALLERY_BUCKET: R2Bucket;
		IMAGES: ImagesBinding;
		CF_ACCESS_TEAM_DOMAIN: "https://chanyakushima.cloudflareaccess.com";
		CF_ACCESS_AUD: "08f4b21524ee5e79efaaa746e84959d1270a483459856b45c9aeb180e4c0941c";
		GALLERY_ENVIRONMENT: "preview";
		GALLERY_CANONICAL_HOST: "chanya.jp";
		GALLERY_ADMIN_EMAIL: string;
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CF_ACCESS_TEAM_DOMAIN" | "CF_ACCESS_AUD" | "GALLERY_ENVIRONMENT" | "GALLERY_CANONICAL_HOST" | "GALLERY_ADMIN_EMAIL">> {}
}
